
name: Run GNU Test

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: write # Publish binary instead of discarding

jobs:
  native:
    name: Run GNU tests (native)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code (uutils/util-linux)
        uses: actions/checkout@v6
        with:
          path: uutils-util-linux
      - name: Checkout code (util-linux/util-linux)
        uses: actions/checkout@v6
        with:
          repository: util-linux/util-linux
          path: gnu-util-linux
          ref: v2.41.4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./uutils-util-linux -> target"
      - name: Install dependencies
        run: |
          sudo apt-get update --quiet
          # omit preinstalled tools <https://github.com/actions/runner-images/tree/main/images/ubuntu>
          sudo apt-get install -y \
            autopoint gettext bc socat ntp squashfs-tools \
            libcap-ng-dev libpam-dev libudev-dev python3-dev libmount-dev libclang-dev libsmartcols-dev
      - name: Build GNU tests
        run: |
          cd gnu-util-linux
          ./autogen.sh
          ./configure
          make -j$(nproc) check-programs
      - name: Download test baseline if exists
        id: download-test-baseline
        continue-on-error: true
        uses: actions/download-artifact@v8
        with:
          name: gnu-test-failures
          path: uutils-util-linux/.reference/

      - name: Run GNU tests & package
        env:
          GNU_PROJECT_DIR: ${{ github.workspace }}/gnu-util-linux
        run: |
          cd uutils-util-linux
          ./scripts/run-tests.sh
          strip -s target/release/util-linux
          zstd -19 target/release/util-linux -o ../util-linux-x86_64-unknown-linux-gnu.zst
      - name: Publish latest commit
        uses: softprops/action-gh-release@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tag_name: latest-commit
          body: |
            commit: ${{ github.sha }}
          draft: false
          prerelease: true
          files: |
            util-linux-x86_64-unknown-linux-gnu.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update test baseline
        if: github.ref == 'refs/heads/main'
        run: |
          cd uutils-util-linux
          ./scripts/check-new-gnu-failures.sh --update-baseline

      - name: Upload test baseline artifact
        if: github.ref == 'refs/heads/main' || steps.download-test-baseline.outcome == 'failure'
        uses: actions/upload-artifact@v7
        with:
          name: gnu-test-failures
          path: uutils-util-linux/.reference/gnu-test-failures.txt
